#!/opt/bin/python
board = []
for j in range(5):
  board.append(["O"] * 5)
def print_board(board):
    for row in board:
        print "".join(row)
board[3][4]='X'
print board
print print_board(board)   
